{{- define "common.deployment" -}}

  {{- $common := dict "Values" .Values.common -}} # Values з common Chart
  {{- $noCommon := omit .Values "common" -}} # Values з основного Chart
  {{- $overrides := dict "Values" $noCommon -}} # записуємо common Values в змінну Values
  {{- $noValues := omit . "Values" -}} # містить усе крім Values, зокрема Chart, Release
  {{- with merge $noValues $overrides $common -}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name_deployment }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}                     # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}                     # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
      labels:
        app: {{ .Values.selector.app }}               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}       # образ Docker
          imagePullPolicy: Never   # вказує k8s, що образ не потрібно завантажувати (варто використовувати лише для випадків, коли образи локальні)
          name: {{ .Values.image.name }}           # ім'я контейнеру
          ports:
            - containerPort: {{ .Values.service.ports.containerPort }} # порт по якому можна звертатись до поди

  {{- end -}}
  {{- end -}}